=== feliciagutmans/XML_Project/DTD7.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
In encoding this text I chose to include some of the most basic structural elements of its genre,
poetry, by outlining the stanzas and line strucutre of the text, as well as denoting the author and 
title of the peom in the beginning of the encoding. 

However, the main work here went into analysing 
the conversational elements in the poems, where Cooper-Clarke seems to be having a chat directly 
with the reader. The main tools that I identified that enabled CC to do this comes from 
1.Making references to things that his readers would be familiar with 
2. Addressing the reader directly, as if speaking to them in person, whether You, I or We. 
Also use of imperative, as if to give advice  or order, as if he is a friend speaking directly 
to the reader.
3. Using colloquial language, including things like swear words and spoken language to make the peoms seem spoken 
4. Making references to people that would be known to his readers, from politicans to 
fictional characters, such that the poems almost seem like gossip in themselves, and to draw the 
viewer in through a sense of common understanding/shared culture. 

At least one of all these four elements are included in every one of his poems, the ones here being
selected randomly based on my own taste, usually more. This establishes CC's pseudo-chat with his 
readers to be a poetic tool that he employs universally.

The form and content elements of this analysis will be kept separate- notably, I will not make any 
comment on the content of the title as this is considered to be a strucutural element so will not
have any bearing on our anaysis of the content of the poem.
-->
<!ELEMENT poem (title, author, stanza+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT  author (#PCDATA|forename|surname)*>
<!ELEMENT  forename (#PCDATA)>
<!ELEMENT  surname (#PCDATA)>
<!--In studying these poems in terms of a discussion between poet and reader,
the tools of referring to something else, directly addressing the reader & the 
poet's own self and colloquial languagr are three key elements to making it
feel like a chat. -->
<!ELEMENT stanza (#PCDATA|line|reference|direct-address|colloquial|person)*>
<!ATTLIST  stanza no CDATA #IMPLIED>
<!ELEMENT  line (#PCDATA |reference|direct-address|colloquial|person)* >
<!ATTLIST  line no CDATA #IMPLIED>
<!ELEMENT  reference (#PCDATA)>
<!ATTLIST  reference type (political|religious|literary|art|pop|place|toy) #IMPLIED >
<!ELEMENT  direct-address (#PCDATA)>
<!ATTLIST  direct-address type (I|you|your|youre|my|we|our|imperative) #IMPLIED >
<!ELEMENT  colloquial (#PCDATA)>
<!ATTLIST  colloquial type (swear|saying|spoken-language) #IMPLIED >
<!ELEMENT  person (#PCDATA)>
<!ATTLIST  person type (pop|political|religious|literary|art|general) #IMPLIED >

=== feliciagutmans/XML_Project/3.Arts_n_Crafts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE poem SYSTEM "DTD7.dtd">
<poem>
    <title>Arts n' Crafts</title>
    <author>
        <forename>John</forename>
        <surname>Cooper-Clarke</surname>
    </author>
    <stanza no="1"> 
        <line no="1">Out of bed into the Shed</line>
        <!--Reference to Alice in Wonderland -->
        <line no="2"><reference type="literary">To paint the wooden roses red</reference></line>
        <!--Reference to rocking horse- a staple of childhood games and therefore pop culture-->
        <line no="3">To ride <reference type="pop">a rocking quadruped</reference></line> 
        <line no="4">With a big idea in <direct-address type="your">your head</direct-address></line>
    </stanza>
    <stanza no="2">
        <!--"Form follows function" core philosophy of 20th century modernist architecture eg. Le Corbusier.
        Reference made explicit in the following line "rudiments of good design", like what modernists said. 
        Note: Mocking mediocre quotidien by contrasting high culture (architectural theory, fine wine) to 
        sheds + melamine tables (Ikea). -->
        <line no="1"><reference type="art">Form and function</reference> in a line</line> 
        <line no="2">The rudiments of good design</line> 
        <line no="3">From the oaken leg to the fine wine</line> 
        <line no="4">To table tops of melamine</line> 
    </stanza>
    <stanza no="3"> 
        <line no="1">There’s nothing that <direct-address type="you">you</direct-address> couldn’t make</line> 
        <line no="2">No effect <direct-address type="you">you</direct-address> couldn’t fake</line>
        <!--Undertone of contempt present throughout his poems. -->
        <line no="3">A pebble sprayed with metal flake</line> 
        <line no="4">Would make a precious paperweight</line> 
    </stanza>
    <stanza no="4">
        <line no="1"><reference type="toy">Teddy bears</reference> to stuff with stuff</line>
        <!--Would not consider "muff" a swear word, but certainly spoken slang. Nylon Mink- luxe/banal-->
        <line no="2">Like nylon mink from a lady’s <colloquial type="spoken-language">muff</colloquial></line> 
        <line no="3">Cotton balls and a powder puff</line> 
        <line no="4"><colloquial type="spoken-language">Pom poms</colloquial> and pocket fluff</line> 
    </stanza>
    <stanza no="5"> 
        <line no="1">Stainless steel and a rock hard aura</line> 
        <line no="2">The marble glance of a lost explorer</line>
        <!--Seems like a random name of an "ordinary", general person. REFERENCE THOUHG?-->
        <line no="3">A heavy heart for the love of <person type="general">Nora</person></line>
        <!--Flower/ daisy chains common element in pop culture, stopping this from being pure metaphor.
        Amphora mainly used to describe vessels from ancient greece. The kind of thing to decorate a garden nowadays.-->
        <line no="4"><reference type="pop">Chains of flowers</reference> on a draped <reference type="art"> amphora </reference></line> 
    </stanza>
    <stanza no="6">
        <!-- Such contempt, so bitter, what an arse.-->
        <line no="1">Time time time to slay</line> 
        <line no="2">Each crowded hour of every day</line> 
        <line no="3">Where indolence is kept at bay</line> 
        <line no="4">In an <colloquial type="spoken-language">arty-crafy</colloquial> <colloquial type="spoken-language">kinda</colloquial>way</line>
    </stanza>
</poem>

=== feliciagutmans/XML_Project/1.Pagan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE poem SYSTEM "DTD7.dtd">
<poem>
    <title>Pagan</title>
    <author>
        <forename>John</forename>
        <surname>Cooper-Clarke</surname>
    </author>
    <stanza no="1">
        <!-- Roses are red, violets are blue = classic pop culture poem that he remixes here -->
        <line no="1"><reference type="pop">Roses are reddish</reference></line>
        <line no="2"><reference type="pop">Violets are blueish</reference></line>
        <line no="3">If it weren’t for <reference type="religious">Christmas</reference></line>
        <line no="4"><direct-address type="we">We</direct-address>’d all be <reference type="religious">Jewish</reference></line>
    </stanza>
    <stanza no="2">
        <line no="1">Get born again</line>
        <line no="2">Like <person type="political">Ronald Reagan?</person></line>
        <line no="3"><colloquial type="spoken-language">No thanks</colloquial></line>
        <line no="4"><direct-address type="I">I</direct-address>’d rather be a <reference type="religious">pagan</reference></line>
    </stanza>
</poem>
